### ISSUE TITLE
2FA Authentification Login Failure

### ISSUE THREAD

**Issue by ghost** [robinhood-unofficial/Robinhood#125]
When I use:

`logged_in = my_trader.login(username="USERNAME HERE", password="PASSWORD HERE", mfa_code="123456")`

I keep getting the following returned:
```
runfile('C:/Users/me/.spyder-py3/temp.py', wdir='C:/Users/Pat/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-10-fc5412ac3587>", line 1, in <module>
    runfile('C:/Users/me/.spyder-py3/temp.py', wdir='C:/Users/Pat/.spyder-py3')

  File "C:\Users\me\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\me\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/me/.spyder-py3/temp.py", line 11, in <module>
    logged_in = my_trader.login(username = "", password = "", mfa_code = "")

  File "C:\Users\me\Documents\Robinhood\Robinhood\Robinhood.py", line 118, in login
    raise RH_exception.LoginFailed()

LoginFailed
```

I'm a noob and I'm totally lost when it comes to the requests library so I can't quite figure out what the issue is here. Can anyone help me out?

**Comment by eXa34** [comment]
OK, so I was able to login by changing my 2fa to 'sms' instead of google authenticator. I posted with username/password, got the mfa_code via text, posted again with the code and it logged me in.

Is there anyway that I can do this by using my Google Authenticator 2FA code instead?
