### ISSUE TITLE
Running example.py leads to a login failed exception being raised.

### ISSUE THREAD

**Issue by chowe77** [robinhood-unofficial/Robinhood#158]
Here's what I'm getting when I try to run example.py with my username and password inputted:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Robinhood/Robinhood.py", line 135, in login
    res.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.robinhood.com/api-token-auth/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    my_trader.login(username="username", password="password")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Robinhood/Robinhood.py", line 138, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed

Has anyone encountered this before?

**Comment by pewpewmcgee** [comment]
I hope that's not your real username/password you left in there

**Comment by pgordon9** [comment]
@chowe77 on the line `my_trader.login(username="username", password="password")`, you need to replace username and password with you actual password. **I highly suggest using environment variables to do this to prevent accidental submittal of your credentials to remote repos.**

**Comment by pgordon9** [comment]
This can be closed.
