### ISSUE TITLE
Invalid Ticker Symbol

### ISSUE THREAD

**Issue by Outlaw782** [robinhood-unofficial/Robinhood#204]
I'm new to this repo, but I was trying to do a symbol print statement using
`
#QR
QR = "myqrcode"
#ROBINHOOD API SETUP
my_trader = Robinhood()
#login
my_trader.login(username="myusername", password="mypass", qr_code = QR)
my_trader.print_quote("AAPL")
`

I am receiving the below error.

It states I am using an invalid ticker symbol, but I am using 'AAPL' as the symbol, so I don't think that's the issue. Has anyone run into this before? I'm assuming it's something very basic that I'm messing up.

```
Traceback (most recent call last):
  File "C:\Users\Zach\PycharmProjects\StockBot\Robinhood\Robinhood.py", line 354, in quote_data
    req.raise_for_status()
  File "C:\Users\Zach\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.robinhood.com/quotes/AAPL/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Zach/PycharmProjects/StockBot/venv/stock1.py", line 46, in <module>
    my_trader.print_quote()
  File "C:\Users\Zach\PycharmProjects\StockBot\Robinhood\Robinhood.py", line 491, in print_quote
    data = self.get_quote_list(stock, 'symbol,last_trade_price')
  File "C:\Users\Zach\PycharmProjects\StockBot\Robinhood\Robinhood.py", line 418, in get_quote_list
    data = self.quote_data(stock)
  File "C:\Users\Zach\PycharmProjects\StockBot\Robinhood\Robinhood.py", line 357, in quote_data
    raise RH_exception.InvalidTickerSymbol()
Robinhood.exceptions.InvalidTickerSymbol
```

**Comment by GoldenEye22** [comment]
@Outlaw782 I think the robinhood server crashed again today, so that might be the issue.

**Comment by Outlaw782** [comment]
@GoldenEye22 Yes that possibly could be it. Are you able to run
 `my_trader.print_quote("AAPL")` 
on your end?

**Comment by Outlaw782** [comment]
I might just wait a few days to try it again

**Comment by ctmandan02** [comment]
same here.  I can only login with 2FA on.  Once I am auth'ed, I can't do anything - quotes, etc.

**Comment by adithyabsk** [comment]
I'm going to consider this issue closed.
