### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

### ISSUE THREAD

**Issue by pranav-manik** [robinhood-unofficial/Robinhood#205]
login issue seems to be back im not sure if this is because I might have 2 factor authentication, I don't believe so though

   ```
 raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    logged_in = my_trader.login(username="username", password="password")
  File "/home/nav/.local/lib/python3.6/site-packages/Robinhood/Robinhood.py", line 122, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed
```

**Comment by GoldenEye22** [comment]
1. Robinhood is currently doing server updates and maintenance 
2. you need 2 factor see #150

**Comment by GoldenEye22** [comment]
also #203

**Comment by Elycin** [comment]
Hello,

I'd like to confirm that this issue exists.

Using the following code I can confirm that the OP's stack trace is identical to mine. It was working fine until this morning in particular so I'm hoping this is more server updates or maintenance.

```py
robinhood_interface = Robinhood()
robinhood_interface.login(
    username=config['robinhood']['username'],
    password=config['robinhood']['password'],
    mfa_code=config['robinhood']['multi_factor_secret']
)
```

```
Traceback (most recent call last):
  File "C:\Users\elyci\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Robinhood\Robinhood.py", line 119, in login
    res.raise_for_status()
  File "C:\Users\elyci\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.robinhood.com/oauth2/token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/elyci/PycharmProjects/robinpi/main.py", line 11, in <module>
    robinhood_interface.login(
  File "C:\Users\elyci\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Robinhood\Robinhood.py", line 122, in login
    raise RH_exception.LoginFailed()
Robinhood.exceptions.LoginFailed

Process finished with exit code 1
```

**Comment by Elycin** [comment]
20 minutes later, the API appears to be back and responding.

**Comment by adithyabsk** [comment]
The login issues have been fixed on master, take a look at the docs. When I have access, I'll be setting up the readthedocs page but everything is in the docs folder.
