### ISSUE TITLE
AttributeError: 'Transaction' object has no attribute 'name'

### ISSUE THREAD

**Issue by joel-liu** [robinhood-unofficial/Robinhood#46]
Hi, I am new to python. I tried the example code for buy_order or sell_order. Here are the error messages. 

/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/Joel/PycharmProjects/Robinhood_AI/try_robinhood.py
Traceback (most recent call last):
  File "/Users/Joel/PycharmProjects/Robinhood_AI/try_robinhood.py", line 7, in <module>
    buy_order = my_trader.place_buy_order(stock_instrument, 1)
  File "/Library/Python/2.7/site-packages/Robinhood/Robinhood.py", line 760, in place_buy_order
    return self.place_order(instrument, quantity, bid_price, transaction)
  File "/Library/Python/2.7/site-packages/Robinhood/Robinhood.py", line 721, in place_order
    'side': transaction.name.lower(),
AttributeError: 'Transaction' object has no attribute 'name'

Process finished with exit code 1

**Comment by joel-liu** [comment]
It is a duplicated issue https://github.com/Jamonek/Robinhood/issues/36 .  Fixed it by upgrade to python 3.
